name: ChatOps Bot - Comment Created
on: 
  issue_comment:
    types: [ created ]
env:
  ALLOW_LIST: "hexylena almahmoud nuwang afgane ksuderman"
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: contains($ALLOW_LIST, github.payload.comment.user.login) && contains(github.event.issue.labels.*.name, 'branch/')
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commands: |
            validate
            plan
            apply
            destroy
            test
  nolabel:
    runs-on: ubuntu-latest
    if: "!contains(github.event.issue.labels.*.name, 'branch/')"
    steps:
      - name: React
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          reaction: -1
