name: ChatOps Bot - Comment Created
on: 
  issue_comment:
    types: [ created ]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: contains('hexylena almahmoud nuwang afgane ksuderman', github.payload.comment.user.login)
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commands: |
            validate
            plan
            apply
            destroy
            show
            test
