name: Explore new features
on:
  repository_dispatch:
    types: [ test-command ]
jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - name: do stuff
        run: echo "Hello world"
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
