name: Explore new features
on:
  repository_dispatch:
    types: [ test-command ]
jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - name: do stuff
        id: branch
        run: |
          label = "${{ github.event.client_payload.github.payload.issue.labels[0].name }}"
          label = $(sed 's|branch/||' <<< $label)
          echo "::set-output name=label::$label
      - name: Echo branch name
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "${{ steps.branch.outputs.label }}
