name: ChatOps Bot - Terraform Plan
on:
  repository_dispatch:
    types: [ plan-command ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
  OS_USERNAME: ${{ secrets.OS_USERNAME }}
  OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
  OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
  OS_PROJECT_DOMAIN_ID: ${{ secrets.OS_PROJECT_DOMAIN_ID }}
  OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
#  OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}          
  OS_USER_DOMAIN_NAME: tacc
  OS_INTERFACE: public
  OS_IDENTITY_API_VERSION: 3

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: testing
      - name: Terraform init
        run: terraform init -input=false        
      - name: Terraform version
        run: terraform --version
      - name: Terraform validate
        run: terraform validate
      - name: Terraform Plan
        id: plan
        run: |
          echo "::set-output name=plan::$(terraform plan -input=false -no-color)"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: ${{ steps.plan.outputs.plan }}      
