name: Validate the Terraform plan
on: push
jobs:
  plan:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'tf skip')"
    steps:
      - uses: actions/checkout@v1
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false        
      - name: Terraform version
        run: terraform --version
      - name: Terraform validate
        run: terraform validate
