name: Deploy infrastructure with Terraform
on:
  push:
    branches:
      - dev
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false        
      - name: Terraform version
        run: terraform --version
      - name: Terraform validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan