name: Deploy infrastructure with Terraform
on:
  push:
    branches:
      - dev
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Terraform version
        run: terraform --version
      - name: Terraform validate
        run: terraform validate
