name: Destroy infrastructure with Terraform
on:
  pull_request:
    types: [ closed ]
    branches:
      - never
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false        
      - name: Terraform version
        run: terraform --version
      - name: Terraform validate
        run: terraform validate
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_DOMAIN_ID: ${{ secrets.OS_PROJECT_DOMAIN_ID }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_ROJECT_NAME }}          
          OS_USER_DOMAIN_NAME: tacc
          OS_INTERFACE: public
          OS_IDENTITY_API_VERSION: 3
        run: terraform destroy -auto-approve -input=false
        