name: ChatOps Bot - Terraform Validate
on:
  repository_dispatch:
    types: [ validate-command ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Terraform init
        run: terraform init -input=false        
      - name: Terraform version
        run: terraform --version
      - name: Terraform validate
        run: terraform validate
