name: ChatOps Bot - Terraform Validate
on:
  repository_dispatch:
    types: [ validate-command ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name from label
        id: branch
        run: |
          label=${{ github.event.client_payload.github.payload.issue.labels[0].name }}
          label=$(sed 's|branch/||' <<< $label)
          echo ::set-output name=label::$label
      - uses: actions/checkout@v1
        with:
          ref: ${{ steps.branch.outputs.label }}
      - name: Terraform init
        run: terraform init -input=false        
      - name: Terraform version
        run: terraform --version
      - name: Terraform Validate
        run: terraform validate
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: "This plan appears to be valid."
